'use strict';Object.defineProperty(exports,'__esModule',{value:true});exports.js=exports.Item=exports.Module=undefined;var _createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if('value'in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor}}();var _lib=require('../lib');var _vm=require('vm');var _vm2=_interopRequireDefault(_vm);var _pProps=require('p-props');var _pProps2=_interopRequireDefault(_pProps);function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj}}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError('Cannot call a class as a function')}}function _possibleConstructorReturn(self,call){if(!self){throw new ReferenceError('this hasn\'t been initialised - super() hasn\'t been called')}return call&&(typeof call==='object'||typeof call==='function')?call:self}function _inherits(subClass,superClass){if(typeof superClass!=='function'&&superClass!==null){throw new TypeError('Super expression must either be null or a function, not '+typeof superClass)}subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,enumerable:false,writable:true,configurable:true}});if(superClass)Object.setPrototypeOf?Object.setPrototypeOf(subClass,superClass):subClass.__proto__=superClass}// Freely extend this class with your custom logic.
var Item=function(_ProtoItem){_inherits(Item,_ProtoItem);function Item(){_classCallCheck(this,Item);return _possibleConstructorReturn(this,(Item.__proto__||Object.getPrototypeOf(Item)).apply(this,arguments))}_createClass(Item,[{key:'mount',value:function mount(){var _this2=this;if(this.isMounted())return Promise.resolve(this);if(!this.data)return Promise.reject('Data not founded.');return new Promise(function(resolve,reject){if(_this2.data.type){// Support for custom type mounter.
_this2.get(_this2.data.type).then(function(typeItem){var type=typeItem.getResult();if(type.mount)type.mount.call(_this2).then(function(){return resolve(_this2)},reject);else resolve(_this2)}).catch(reject)}else{// Support for non-stored, system data types.
_this2.getResult=function(){return _this2.data.result};resolve(_this2)}}).then(function(item){if(!item.isMounted())throw new Error('Item { id: "'+_this2.data.id+'", type: "'+_this2.data.type+'" } is not mounted. Type not define getResult method.');return item})}},{key:'unmount',value:function unmount(){var _this3=this;if(!this.isMounted())return Promise.resolve(this);delete this.getResult;return Promise// Unmount and unset childs before try unmount current item.
.all(Object.keys(this.childs).map(function(c){return _this3.childs[c].unmount().then(function(child){return _this3.unset(child)})})).then(function(){// System non-stored data, is not unmountable.
if(!_this3.data.type)return _this3;// Load custom type unmounter.
return _this3.get(_this3.data.type).then(function(typeItem){var type=typeItem.getResult();if(type.unmount)return type.unmount.call(_this3);else _this3}).then(function(){return _this3})})}}]);return Item}(_lib.Item);/**
 * @name Item#data
 * @type {Link=}
 *//**
 * @interface Data
 *//**
 * @name Data#id
 * @type {string=}
 *//**
 * @name Data#type
 * @type {string=}
 * @descirption
 * If is undefined, result gets from data.result directly, without mounting.
 */var Module=function Module(id,item){this.id=id;this.children=[];this.parent=null;this.loaded=false;this.exports={};this.item=item};var js={result:{mount:function mount(){var _this4=this;var module=new Module(this.data.id,this);this.getResult=function(){return module.exports};var childs={};if(this.data.childs)for(var c in this.data.childs){childs[c]=function(c){return _this4.get(_this4.data.childs[c]).then(function(child){_this4.set(c,child);return child})}(c)}return(0,_pProps2.default)(childs).then(function(childs){_vm2.default.runInNewContext(_this4.data.code,{module:module,require:function require(name){return childs[name].getResult?childs[name].getResult():undefined}});return _this4})}}};exports.Module=Module;exports.Item=Item;exports.js=js;
//# sourceMappingURL=implementation.js.map